# landing_simbad/cloudbuild.simbad.yaml
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOST: 'us-docker.pkg.dev'
  _AR_REPO: 'containers'
  _REGION: 'us-west2'
  _SERVICE: 'simbad-harvester'
  _SA_EMAIL: 'run-landing-simbad-sa@${PROJECT_ID}.iam.gserviceaccount.com'
  _GCS_BUCKET: 'TU_BUCKET'
  _LANDING_PREFIX: 'landing/simbad'
  _SB_TIPO_ENTIDAD: 'AAyP'
  _SB_START_YEAR: '2012'
  _SB_DATASET: 'simbad_carteras_aayp_hipotecarios'
  _SB_KEEP_MONTHLY: 'false'
  _SB_API_KEY_SECRET: 'sb_api_key'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}
      - -f
      - landing_simbad/Dockerfile
      - landing_simbad      # <--- build context aquí

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --service-account=${_SA_EMAIL}
      - --no-allow-unauthenticated
      - --memory=2Gi
      - --cpu=2
      - --max-instances=4
      - --timeout=3600
      - --set-env-vars=GCS_BUCKET=${_GCS_BUCKET},LANDING_PREFIX=${_LANDING_PREFIX},SB_TIPO_ENTIDAD=${_SB_TIPO_ENTIDAD},SB_START_YEAR=${_SB_START_YEAR},SB_DATASET=${_SB_DATASET},SB_KEEP_MONTHLY=${_SB_KEEP_MONTHLY}
      - --set-secrets
      - SB_API_KEY=${_SB_API_KEY_SECRET}:latest

images:
  - ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}
