# job.simbad.yaml
apiVersion: run.googleapis.com/v2
kind: Job
metadata:
  name: simbad-harvester-job
  annotations:
    run.googleapis.com/description: "Descarga SIMBAD y sube CSV a GCS (AAyP Hipotecarios)"
template:
  template:
    containers:
    - image: us-docker.pkg.dev/PROJECT_ID/containers/simbad-harvester:TAG
      command: ["python"]
      args: ["-m", "simbad.runner"]
      env:
      - name: GCS_BUCKET
        value: TU_BUCKET
      - name: LANDING_PREFIX
        value: landing/simbad
      - name: SB_TIPO_ENTIDAD
        value: AAyP
      - name: SB_START_YEAR
        value: "2012"
      - name: SB_DATASET
        value: simbad_carteras_aayp_hipotecarios
      - name: SB_KEEP_MONTHLY
        value: "false"
      - name: SB_API_KEY
        valueSource:
          secretKeyRef:
            secret: sb_api_key
            version: "latest"
      resources:
        cpuIdle: false
        limits:
          cpu: "2"
          memory: 2Gi
    taskTimeout: 21600s
    taskCount: 1
    maxRetries: 1
  labels:
    app: simbad
