# SIMBAD Incremental Job - Para ejecución programada con Cloud Scheduler
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-west2
  _AR_HOST: us-west2-docker.pkg.dev
  _AR_REPO: containers
  _IMAGE: simbad-incremental
  _JOB: simbad-incremental-job
  _SERVICE_ACCOUNT: 51026942179-compute@developer.gserviceaccount.com
  _BUCKET: dae-integrador-2025
  _SB_SECRET: sb_api_key
  _SB_LOOKBACK_MONTHS: "3"
  _IMAGE_TAG: "latest"  # Por defecto 'latest', puede ser sobrescrito por triggers

steps:
# 1) Build
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}', 'landing/simbad/incremental' ]

# 2) Push
- name: gcr.io/cloud-builders/docker
  args: [ 'push', '${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}' ]

# 3) Crear/actualizar Job incremental
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      # Check if job exists to determine action
      if gcloud run jobs describe ${_JOB} --region ${_REGION} >/dev/null 2>&1; then
        echo "Job exists, updating..."
        gcloud run jobs update ${_JOB} \
      else
        echo "Job does not exist, creating..."
        gcloud run jobs create ${_JOB} \
      fi \
        --region ${_REGION} \
        --image ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG} \
        --service-account ${_SERVICE_ACCOUNT} \
        --task-timeout=30m \
        --max-retries=2 \
        --set-env-vars=GCS_BUCKET=${_BUCKET} \
        --set-env-vars=LANDING_PREFIX=lakehouse/landing/simbad \
        --set-env-vars=SB_TIPO_ENTIDAD=AAyP \
        --set-env-vars=SB_DATASET=simbad_carteras_aayp_hipotecarios \
        --set-env-vars=SB_LOOKBACK_MONTHS=${_SB_LOOKBACK_MONTHS} \
        --set-env-vars=PYTHONUNBUFFERED=1 \
        --set-env-vars=SB_API_KEY=dff2111ccbcd44c2ac47265b658949f3 \
        --labels=type=incremental,purpose=scheduled

images:
- ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}