options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "simbad-incremental"
  _REGION: "us-west2"
  _BUCKET: "dae-integrador-2025"
  _LANDING_PREFIX: "lakehouse/landing/simbad"
  _SB_API_KEY: "dff2111ccbcd44c2ac47265b658949f3"   # usa Secret Manager si prefieres
  _SB_TIPO_ENTIDAD: "AAyP"
  _SB_DATASET: "simbad_carteras_aayp_hipotecarios"
  _SB_LOOKBACK_MONTHS: "3"

steps:
  # 1) Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'landing/simbad/incremental'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/simbad-incremental:$SHORT_SHA'
      - '.'

  # 2) Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/simbad-incremental:$SHORT_SHA'

  # 3) Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'landing/simbad/incremental'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/simbad-incremental:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - >-
        GCS_BUCKET=${_BUCKET},
        LANDING_PREFIX=${_LANDING_PREFIX},
        SB_API_KEY=${_SB_API_KEY},
        SB_TIPO_ENTIDAD=${_SB_TIPO_ENTIDAD},
        SB_DATASET=${_SB_DATASET},
        SB_LOOKBACK_MONTHS=${_SB_LOOKBACK_MONTHS}
      - '--timeout=600s'  # 10 minutos suficientes para incremental
      - '--cpu=1'
      - '--memory=1Gi'
      - '--allow-unauthenticated'  # Permitir acceso para scheduler

images:
  - 'gcr.io/$PROJECT_ID/simbad-incremental:$SHORT_SHA'