# SIMBAD Incremental Job - Para ejecución programada con Cloud Scheduler
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-west2
  _AR_HOST: us-west2-docker.pkg.dev
  _AR_REPO: containers
  _IMAGE: simbad-incremental
  _JOB: simbad-incremental-job
  _SERVICE_ACCOUNT: 51026942179-compute@developer.gserviceaccount.com
  _BUCKET: dae-integrador-2025
  _SB_SECRET: sb_api_key
  _SB_LOOKBACK_MONTHS: "3"
  _IMAGE_TAG: "latest"  # Por defecto 'latest', puede ser sobrescrito por triggers

steps:
# 1) Build
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}', 'landing/simbad/incremental' ]

# 2) Push
- name: gcr.io/cloud-builders/docker
  args: [ 'push', '${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}' ]

# 3) Deploy as Cloud Run Service (simplificado)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_JOB}'
    - '--image'
    - '${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GCS_BUCKET=${_BUCKET},LANDING_PREFIX=lakehouse/landing/simbad,SB_TIPO_ENTIDAD=AAyP,SB_DATASET=simbad_carteras_aayp_hipotecarios,SB_LOOKBACK_MONTHS=${_SB_LOOKBACK_MONTHS},SB_API_KEY=dff2111ccbcd44c2ac47265b658949f3'

images:
- ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${_IMAGE_TAG}