# cloudbuild/cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "landing-scraper"
  _REGION: "us-west2"
  _BUCKET: "dmc_proy_storage"

steps:
  # 1) Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/landing-scraper:$SHORT_SHA'
      - '.'

  # 2) Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/landing-scraper:$SHORT_SHA'

  # 3) Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/landing-scraper:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'GCS_BUCKET=${_BUCKET},LANDING_PREFIX=landing/macroeconomics,POWERBI_RESOURCE_KEY=d2d3b042-b343-4f05-85cb-be05eb64dd22,PORT=8080'
      - '--timeout=900'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/landing-scraper:$SHORT_SHA'
