options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "landing-scraper"
  _REGION: "us-west2"
  _IMAGE: "gcr.io/$PROJECT_ID/landing-scraper:$SHORT_SHA"
  _BUCKET: "dmc_proy_storage"

steps:
  # 1) Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'landing_run'
    args: ['build','-t','${_IMAGE}','.']

  # 2) Push  (imprescindible para que Cloud Run la encuentre)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_IMAGE}']

  # 3) Deploy (sin --allow-unauthenticated por la política)
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'landing_run'
    args:
      [
        'run','deploy','${_SERVICE}',
        '--image','${_IMAGE}',
        '--region','${_REGION}','--platform','managed',
        '--set-env-vars','GCS_BUCKET=${_BUCKET},LANDING_PREFIX=landing'
      ]

images:
  - '${_IMAGE}'
