options:
  logging: CLOUD_LOGGING_ONLY  # evita el error de logs en Gen2

substitutions:
  _SERVICE: "landing-scraper"
  _REGION: "us-west2"
  _BUCKET: "dmc_proy_storage"

steps:
  # Construir la imagen Docker desde landing_run/
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'landing_run'
    args: ['build','-t','gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA','.']

  # Desplegar a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'landing_run'
    args: [
      'run','deploy','${_SERVICE}',
      '--image','gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA',
      '--region','${_REGION}',
      '--platform','managed',
      '--set-env-vars','GCS_BUCKET=${_BUCKET},LANDING_PREFIX=landing',
      '--allow-unauthenticated'   # quítalo si quieres acceso solo con IAM
    ]

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA'
