options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: bash
  args:
  - -ceu
  - |
    chmod +x scripts/run-harvester.sh
    ./scripts/run-harvester.sh
