# landing_simbad/Dockerfile  (contexto = landing_simbad/)
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT=8080

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
  && rm -rf /var/lib/apt/lists/*

# OJO: sin prefijo 'landing_simbad/' porque el contexto es ESTA carpeta
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080
CMD ["uvicorn", "main_simbad:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]
